version: "3.9"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/gameofy.publicvm.com:/etc/letsencrypt/live/gameofy.publicvm.com:ro
      - /etc/letsencrypt/archive/gameofy.publicvm.com:/etc/letsencrypt/archive/gameofy.publicvm.com:ro
    depends_on:
      - webapp
      - gateway
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en2c-users:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=/api
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en2c-webapp:latest
    expose:
      - "80"
    depends_on:
      - gateway
    networks:
      - monitor-net

  gateway:
    build: ./gateway
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_en2c-gateway:latest
    expose:
      - "8080"
    environment:
      - USERS_BASE_URL=http://users:3000
      - GAMEY_BASE_URL=http://gamey:4000
    depends_on:
      - users
      - gamey
      - authentication
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en2c-gamey:latest
    expose:
      - "4000"
    networks:
      - monitor-net

  authentication:
    build: ./authentication
    container_name: authentication
    image: ghcr.io/arquisoft/yovi_en2c-authentication:latest
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=24h
    networks:
      - monitor-net

  bot-api:
    build: ./bot-api
    container_name: bot-api
    environment:
      - GAMEY_BASE_URL=http://gamey:4000
      - PORT=6000
    depends_on:
      - gamey
    expose:
      - "6000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=12h"
      - "--storage.tsdb.retention.size=256MB"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net

volumes:
  loki-data:
  grafana-data:
  prometheus-data:

networks:
  monitor-net:
    driver: bridge