version: "3.9"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/gameofy.publicvm.com:/etc/letsencrypt/live/gameofy.publicvm.com:ro
      - /etc/letsencrypt/archive/gameofy.publicvm.com:/etc/letsencrypt/archive/gameofy.publicvm.com:ro
    depends_on:
      - webapp
      - gateway
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en2c-users:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=https://gameofy.publicvm.com:8080
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en2c-webapp:latest
    expose:
      - "80"
    depends_on:
      - gateway
    networks:
      - monitor-net

  gateway:
    build: ./gateway
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_en2c-gateway:latest
    expose:
      - "8080"
    environment:
      - USERS_BASE_URL=http://users:3000
      - GAMEY_BASE_URL=http://gamey:4000
    depends_on:
      - users
      - gamey
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en2c-gamey:latest
    expose:
      - "4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge