sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_en2d
sonar.projectName=yovi_en2d

sonar.sources=webapp/src,users,gamey/src,gateway/gateway-service.js,authentication,bot-api/src

sonar.tests=webapp/src,users/__tests__,gamey/src,gateway/__tests__,authentication/tests,bot-api/tests

sonar.test.inclusions=**/*.test.tsx,**/*.test.js

sonar.javascript.lcov.reportPaths=\
webapp/coverage/lcov.info,\
users/coverage/lcov.info,\
gateway/coverage/lcov.info,\
authentication/coverage/lcov.info,\
bot-api/coverage/lcov.info

sonar.rust.lcov.reportPaths=gamey/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**